name: PlayTime
main: dev.foolen.playtime.PlayTimePlugin
version: 1.0

commands:
  playtime:
    usage: /<command>
    description: Shows total online playtime

permissions:
  playtime.playtime:
    description: Grants access to /playtime command
    default: op